
# created by M. van Beekveld
# simple file to convert slha file generated by suspect, spheno etc. to madgraph input
##########
# set your MG5 dir here, since it needs the converter in Madgraph. 
import sys
sys.path.append('/home/radam/Madgraph/MG5_aMC_v2_9_5')
import models.check_param_card as converter

# set slhafile to generated file
# outputfile is name_original_file(.dat)_converted.dat
import fileinput

for slhafile in sys.argv[1:]:
    output_path = slhafile.replace("output.slha2","")+"param_card.dat"
    converter.convert_to_mg5card(slhafile, output_path)

    #read in file
    with open(output_path,'r') as f:
        data = f.readlines()
    #edit line
    for i in range(len(data)):
        if 'DECAY' in data[i] or '-->' in data[i]:
            continue
        for entry in data[i].split():
            try:
                float(entry)
            except ValueError:
                continue
            if abs(float(entry)) < 1e-10:
                data[i] = data[i].replace(str(entry), '0')
            
        if "BLOCK MASS" in data[i]:
            data[i] = "BLOCK MASS #\n      23 9.11876e+01\n      15 1.77e+00\n      6 1.750e+02\n"
        if "VCKMIN" in data[i]:
            data[i] = data[i].replace("VCKMIN", "VCKM")
        if "UPMNSIN" in data[i]:
            data[i] = data[i].replace("UPMNSIN", "UPMNS")
        if "ALPHA" in data[i]:
            data[i] = data[i].replace("ALPHA", "FRALPHA")
        
            
        
    #write file
    with open(output_path,'w') as f:
        f.writelines(data)

    print("Converted file is "+output_path)

